language: cpp
sudo: false
addons:
  apt:
    packages:
    - build-essential
    - ninja-build
    - python2.7
    - git
    - wget
    - graphviz
    - gnuplot
branches:
    only:
        - dev
        - master
stages:
  - sheldon
  - build_doc
  #- deploy_doc
compiler:
    - gcc
before_script:
    - git clone --depth 1 -b travis https://github.com/fw4spl-org/fw4spl-git.git fw4spl-git
    - cd fw4spl-git
    - git config --global codingstyle-hook.uncrustify-path `pwd`/hooks/uncrustify
    - cd ..
    - wget -q --no-check-certificate https://cmake.org/files/v3.4/cmake-3.4.1-Linux-x86_64.tar.gz
    - tar xzf cmake-3.4.1-Linux-x86_64.tar.gz > /dev/null
    - wget -q --no-check-certificate http://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.11.linux.bin.tar.gz
    - tar xzf doxygen-1.8.11.linux.bin.tar.gz > /dev/null
    - export CMAKE_BIN=$TRAVIS_BUILD_DIR/cmake-3.4.1-Linux-x86_64/bin/cmake
    - export DOXYGEN_BIN=$TRAVIS_BUILD_DIR/doxygen-1.8.11/bin/doxygen
    - mkdir -p build/Documentation/Doxygen/html
    - cd build/Documentation/Doxygen/html
    - git clone https://github.com/fw4spl-org/fw4spl-dox.git .
    - git checkout --quiet --orphan $TRAVIS_BRANCH
    - git reset --hard
    - git clean -f -d
    - cd $TRAVIS_BUILD_DIR/build
    - $CMAKE_BIN -DCMAKE_INSTALL_PREFIX:PATH=/tmp $TRAVIS_BUILD_DIR/ -DCMAKE_BUILD_TYPE:STRING=Debug -DBUILD_DOCUMENTATION:BOOL=ON -DBUILD_TESTS:BOOL=OFF -DDOXYGEN_EXECUTABLE:FILEPATH=$DOXYGEN_BIN -DENABLE_PCH:BOOL=OFF
    - cd $TRAVIS_BUILD_DIR
jobs:
  include:
    - stage: sheldon
      script:
        # Fix commit range in Travis, if set.
        # See: https://github.com/travis-ci/travis-ci/issues/4596
        - fw4spl-git/hooks/sheldon ${TRAVIS_COMMIT_RANGE/.../..}
    - stage: build_doc
      script:
        - cd $TRAVIS_BUILD_DIR/build
        - make doc
    - stage: deploy_doc
      script:
        - git config --global user.name 'travis'
        - git config --global user.email 'travis'
        - cd $TRAVIS_BUILD_DIR/build/Documentation/Doxygen/html
        - git add --all .
        - git commit -m "Auto-updating Doxygen developer documentation"
        - git push https://$GITHUB_API_KEY@github.com/fw4spl-org/fw4spl-dox.git $TRAVIS_BRANCH --quiet --force > /dev/null 2>&1
